### ISSUE TITLE
MQTT not working for Schellenberg covers after 3.9 Update

### ISSUE THREAD

**Issue by Barry-Ricoh** [GimpArm/smartfriends-bridge#4]
Hi,
as i wrote my Schellenberg covers not working anymore after the 3.9 Update.
I am using mqtt.
But no error in Log.

**Comment by GimpArm** [comment]
No error at all? Like nothing in the logs? Did you update the ShcVersion and ShApiVersion? I assume you reset the SmartFriends hub and this bridge service?

**Comment by Barry-Ricoh** [comment]
Hi, no not any error.
MQTT Explorer shows Status and commands.
ShcVersion (3.4.5) and ShApi (3.3) updated in config.
How do i reset the HUB? I restarted it, using "Powe OFF"
Is reset something different?
Is the configuration of the hub lost bei resetting?
How do i reset bridge service?
Restarted HA mor then 1 time also complete Raspi new started.
After restoring to 3.8 also not working anymore.
I am completly without idea.

I will write in the HA Community.
Maybe its a little faster and easier.

**Comment by Barry-Ricoh** [comment]
I found a solution by myself.
The Id has changed.

`[
  {
    "id": 19322,
    "name": "Rollo",
    "room": "LivingRoom",
    "gatewayDevice": "SmartFriendsBox",
    "kind": "RollingShutter",
    "manufacturer": "Alfred Schellenberg GmbH",
    "state": 1,
    "devices": {
      "rollingShutter": {
        "Id": 11291,
        "description": "SchellenbergRadioMotor_Unidirectional",
        "commands": {
          "Stop": 0,
          "Up": 1,
          "Down": 2
        },
        "currentValue": 1
      }
    }
  },
  {
    "id": 4081,
    "name": "Rolladen",
    "room": "Badezimmer",
    "gatewayDevice": "SmartFriendsBox",
    "kind": "RollingShutter",
    "manufacturer": "Alfred Schellenberg GmbH",
    "state": 1,
    "devices": {
      "rollingShutter": {
        "Id": 10114,
        "description": "SchellenbergRadioMotor_Unidirectional",
        "commands": {
          "Stop": 0,
          "Up": 1,
          "Down": 2
        },
        "currentValue": 1
      }
    }
  }
]`

I dont know why, but before there where no 2 different Id´s
The first cover has id “19322” and “11291”.
Before ist only has the “11291”.
Now i changes to “19322” and it works again.
Same with the second cover.
Changing 10114 to 4081 in the “deviceMap.json” did the trick.

Hope it helps someone.
